apiVersion: v1
kind: Secret
metadata:
  name: monitor-secrets
type: Opaque
stringData:
  SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/xxx/yyy/zzz"
  TELEGRAM_BOT_TOKEN: ""
  TELEGRAM_CHAT_ID: ""

